### ISSUE TITLE
Remove "exceptions" dependency.

### ISSUE THREAD

**Issue by danidiaz** [haskell-streaming/streaming#31] opened 2017-12-09 18:19 UTC
This package depends on [exceptions](http://hackage.haskell.org/package/exceptions-0.8.3) but, after searching for `Control.Monad.Catch` in the repo, I can't find any reference. Perhaps the dependency could be dropped?

**Comment by andrewthad** [comment] 2017-12-09 19:06
Thanks. Fixed with 2e840128d833eba46b6f8fe8abb6d0fa5d14d0d5.

**Closed by andrewthad** 2017-12-09 19:06 UTC

**Comment by ocharles** [comment] 2018-01-02 14:55
Why was `MonadCatch` removed? It's also not in the changelog.

**Comment by jkarni** [comment] 2018-02-26 11:04
I'm also a little unclear on why `MonadMask` was removed along with it. It seems like the [discussion](#13) around `resourcet` suggests using bracket-style (e.g. `streaming-with`) computations instead, but how does one do that at all without the instance?

**Comment by danidiaz** [comment] 2018-02-26 17:42
@jkarni Looking at previous versions of _streaming_, it seems that `Stream` was never an instance of `MonadMask`.

> but how does one do that at all without the instance?

I'm not familiar with _streaming-with_, but I suppose one could create and consume the `Stream` inside the `bracket`.

**Comment by jkarni** [comment] 2018-02-26 18:10
Sorry, I should have been clearer - it was removed [here](https://github.com/haskell-streaming/streaming/commit/6348134193178b82cb5baf9049a89ed8f70667bb) (though I think it was removed before it was ever released?), and discussed as an alternative to `resourcet` [here](https://github.com/michaelt/streaming/issues/23)

**Comment by ocharles** [comment] 2018-03-22 14:22
Yes, as shown there was an instance of `MonadMask` which vanished with no discussion.

**Comment by ocharles** [comment] 2018-07-01 09:43
FWIW, I'm pretty sure we definitely can't have `MonadMask` now that `exceptions-0.10` is out. This requires an implementation of `generalBracket`, but this cannot be safely written AFAICT. The problem is `take` would stop resource cleanup from happening. I don't think it was sound in the first place. I'll have more of a think on this, but I think it's unfortunately fundamental.
